### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by Zerboxx** [m1llashendj/WarzoneExternalCheat#1]
i can't find .sln file?

**Comment by hendodev** [comment]
this is a rat.

**Comment by xii69** [comment]
> this is a rat.

do you've a working one?

**Comment by hendodev** [comment]
> > this is a rat.
> 
> do you've a working one?

i sell my own

**Comment by xii69** [comment]
> > > this is a rat.
> > 
> > 
> > do you've a working one?
> 
> i sell my own

gimme ur discord id, mine is: xii69

**Comment by hendodev** [comment]
> > > > this is a rat.
> > > 
> > > 
> > > do you've a working one?
> > 
> > 
> > i sell my own
> 
> gimme ur discord id, mine is: xii69

added accept mine = nullbyte_1
